name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Theos environment
        uses: Arthur404Dev/set-up-theos@master

      - name: Compile and Package
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        
      - name: Upload 成品 DEB 大包
        uses: actions/upload-artifact@v4
        with:
          name: universalhijack_rootless_deb
          path: packages/*.deb
