name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup iOS Toolchain, SDK and Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y perl clang make git rsync curl
          
          # 1. 克隆官方 Theos 环境
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          
          # 2. 【100% 稳妥修复】放弃容易 404 的 Release 页面，直接用 Git 协议拉取官方 Linux 编译器
          mkdir -p $HOME/theos/toolchain/linux/iphone
          git clone --depth=1 https://github.com/theos/toolchain.git $HOME/official_toolchain
          
          # 3. 把里面解压好的 Linux 编译器核心文件强行平移过去
          cp -r $HOME/official_toolchain/linux/iphone/* $HOME/theos/toolchain/linux/iphone/
          rm -rf $HOME/official_toolchain
          
          # 4. 【100% 你亲测可用】创建 SDK 存放目录并拉取无根 SDK
          mkdir -p $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/official_sdks
          cp -r $HOME/official_sdks/iPhoneOS14.5.sdk $HOME/theos/sdks/
          rm -rf $HOME/official_sdks

      - name: Compile and Package
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        
      - name: Upload 成品 DEB 大包
        uses: actions/upload-artifact@v4
        with:
          name: universalhijack_rootless_deb
          path: packages/*.deb
