name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup iOS Toolchain, SDK and Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y perl clang make git rsync curl xz-utils
          
          # 1. 克隆官方 Theos 环境
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          
          # 2. 【绝对保险】下载官方指定、对 Ubuntu 24 兼容性最好的跨平台编译器
          mkdir -p $HOME/theos/toolchain/linux/iphone
          curl -LO https://github.com/theos/toolchain/releases/download/linux-arm64/iphone-toolchain.tar.lzma
          tar -xf iphone-toolchain.tar.lzma -C $HOME/theos/toolchain/linux/iphone --strip-components=1
          rm iphone-toolchain.tar.lzma
          
          # 3. 创建 SDK 存放目录并拉取 iOS 14.5 SDK
          mkdir -p $HOME/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $HOME/official_sdks
          cp -r $HOME/official_sdks/iPhoneOS14.5.sdk $HOME/theos/sdks/
          rm -rf $HOME/official_sdks

      - name: Compile and Package
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
        
      - name: Upload 成品 DEB 大包
        uses: actions/upload-artifact@v4
        with:
          name: universalhijack_rootless_deb
          path: packages/*.deb
